import {assetPath} from './paths';
import Image from 'next/image';
import BookingForm from '@/components/booking-form';
import ServiceMenu from '@/components/service-menu';
const faq=[
 ['Mình chưa biết chọn dịch vụ nào, có đặt lịch được không?','Được. Chọn “Mình cần Xile tư vấn” trong form hoặc gọi 0909 722 408. Bạn có thể trao đổi nhu cầu, sản phẩm đang dùng và điều mình mong muốn trước khi chọn dịch vụ.'],
 ['Các mức giá trong khoảng được tính như thế nào?','Peel mụn, Peel Glass Skin, Peel lưng và Thu nhỏ lỗ chân lông có khoảng giá theo bảng dịch vụ. Xile sẽ trao đổi lựa chọn và xác nhận mức giá cụ thể trước khi bạn quyết định.'],
 ['Peel, vi kim và cấy HA có phù hợp với mình không?','Tên dịch vụ chưa đủ để xác định có phù hợp với làn da của bạn. Hãy trao đổi rõ phương pháp, sản phẩm sử dụng, người thực hiện và cách chăm sóc sau buổi trước khi đặt lịch. Không tự chọn chỉ theo tên gói hoặc giá.'],
 ['Có cam kết hết mụn, hết thâm sau một buổi không?','Không có cam kết như vậy trên trang này. Làn da và mức đáp ứng của mỗi người khác nhau; mục tiêu chăm sóc cần được trao đổi thực tế, không dựa vào lời hứa thay đổi ngay lập tức.'],
 ['Mỗi dịch vụ kéo dài bao lâu?','Thời lượng và các bước cụ thể sẽ được Xile xác nhận khi trao đổi lịch. Bạn hãy cho Xile biết khoảng thời gian mình có thể sắp xếp.'],
 ['Điền form là đã đặt lịch thành công chưa?','Chưa. Form hiện giúp bạn soạn nội dung để gửi qua Facebook. Lịch chỉ được xác nhận sau khi Xile và bạn thống nhất dịch vụ, giá và khung giờ. Bạn cũng có thể gọi trực tiếp để trao đổi.']
];
function Brand(){return <a href="#" className="brand" aria-label="Xile Beauty Spa — về đầu trang"><Image src={assetPath("/xile-logo.png")} width={500} height={500} alt="Xile Beauty & Spa" priority/></a>}
function CTA({children='Đặt lịch tư vấn da'}:{children?:React.ReactNode}){return <a className="button" href="#dat-lich">{children}<span aria-hidden>↗</span></a>}
export default function Home(){return <>
<a className="skip" href="#noi-dung">Đến nội dung chính</a>
<header><div className="nav-shell"><Brand/><nav aria-label="Điều hướng chính"><a href="#cach-cham">Cách Xile chăm da</a><a href="#bang-gia">Dịch vụ & bảng giá</a><a href="#hoi-dap">Điều bạn muốn biết</a></nav><a className="nav-cta" href="#dat-lich">Đặt lịch <span aria-hidden>↗</span></a></div></header>
<main id="noi-dung">
<div className="hero-stage"><section className="hero wrap"><div className="hero-copy"><p className="eyebrow">XILE BEAUTY SPA · CHĂM SÓC DA</p><h1>Lắng nghe làn da<br/>{' '}<em>Chăm mình từ những<br className="desktop-break"/>{' '}điều dịu dàng.</em></h1><p className="lead">Gạt đi lớp bụi ngày dài, dành một khoảng riêng để làn da được quan tâm. Cùng Xile tìm lựa chọn chăm sóc phù hợp với bạn.</p><div className="hero-actions"><CTA/><a className="text-link" href="#bang-gia">Khám phá dịch vụ ↓</a></div><div className="hero-details"><span><strong>Từ 250.000đ</strong>Chăm sóc da cơ bản</span><span><strong>67 Hưng Phú</strong>Quận 8 · TP. Hồ Chí Minh</span></div></div><figure className="hero-photo"><Image src={assetPath("/skin-care.webp")} alt="Nhân viên Xile chăm sóc da cho khách trong không gian ánh sáng ấm" width={1100} height={1467} priority/><figcaption><span>MỘT KHOẢNH KHẮC TẠI XILE</span><p>Chăm da bằng sự chú tâm.</p></figcaption><span className="photo-index" aria-hidden>01 / XILE</span></figure></section></div>
<div className="motto"><span>LÀM SẠCH</span><i aria-hidden>✧</i><span>CHĂM SÓC</span><i aria-hidden>✧</i><span>KIÊN NHẪN VỚI LÀN DA</span></div>
<section className="section wrap problem"><div><p className="eyebrow">01 / CÓ THỂ BẠN CŨNG TỪNG</p><h2>Muốn da đẹp hơn<br/>{' '}Nhưng chưa biết <em>bắt đầu từ đâu?</em></h2></div><div className="concerns">{[['Da có nhiều điều khiến bạn bận tâm','Dầu, mụn, thâm hay cảm giác thiếu ẩm khiến mỗi lần chọn cách chăm sóc lại thêm phân vân.'],['Quá nhiều lựa chọn, quá ít sự rõ ràng','Bạn muốn hiểu mình đang chọn gì, giá bao nhiêu và điều gì cần trao đổi trước buổi chăm sóc.'],['Chỉ muốn được chăm chút cho mình','Sau một ngày dài, đôi khi bạn cần một buổi chăm da và một khoảng nghỉ thật riêng']].map(([t,d],i)=><article key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
<section className="approach" id="cach-cham"><div className="wrap section"><div className="section-head"><p className="eyebrow">02 / CHĂM DA CÙNG XILE</p><h2>Hiểu điều da cần<br/>{' '}<em>Rồi mới chọn cách chăm.</em></h2><p>Một lựa chọn dễ an tâm hơn khi bạn hiểu rõ dịch vụ và có thời gian trao đổi.</p></div><div className="benefits">{[['01','Có điểm bắt đầu rõ ràng','Tìm dịch vụ theo nhu cầu: làm sạch & chăm sóc, peel hoặc phục hồi chuyên sâu.'],['02','Chủ động với chi phí','Xem bảng giá trước, trao đổi giá cụ thể với những dịch vụ có khoảng giá.'],['03','Có tiếng nói trong lựa chọn','Nói với Xile điều bạn quan tâm, cảm giác của da và mong muốn của mình trước khi quyết định.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="section wrap real"><figure><Image src={assetPath("/skin-detail.webp")} width={1100} height={1467} alt="Ảnh thực tế thao tác chăm sóc và lấy nhân mụn tại Xile"/><figcaption>Ảnh thực tế do Xile cung cấp</figcaption></figure><div><p className="eyebrow">03 / NHỮNG KHOẢNH KHẮC LÀM NGHỀ</p><h2>Sự chăm chút<br/>{' '}nằm trong <em>từng thao tác.</em></h2><p className="lead">Một buổi chăm da tại Xile, được ghi lại bằng những hình ảnh thật. Bạn có thể ghé trang Facebook để tìm hiểu thêm và trò chuyện trực tiếp trước khi đến.</p><a className="text-link" href="https://www.facebook.com/xilebeautyspa/" target="_blank" rel="noopener noreferrer">Ghé Xile Beauty Spa trên Facebook ↗</a><div className="real-address"><small>HẸN BẠN TẠI</small><p>67 Hưng Phú, Quận 8<br/>{' '}TP. Hồ Chí Minh</p></div></div></section>
<section className="pricing section" id="bang-gia"><div className="wrap"><div className="section-head"><p className="eyebrow">04 / DỊCH VỤ & BẢNG GIÁ</p><h2>Một làn da riêng<br/>{' '}<em>Một lựa chọn dành cho bạn.</em></h2><p>Chạm vào tên dịch vụ để chọn trong form tư vấn. Chi tiết phương pháp và mức giá sẽ được xác nhận trước khi thực hiện.</p></div><ServiceMenu/><div className="price-note"><strong>Bạn chưa cần chọn ngay.</strong><p>Với peel, vi kim và cấy HA, hãy trao đổi kỹ về phương pháp và sự phù hợp trước khi quyết định. Tên dịch vụ được giữ theo bảng giá Xile cung cấp.</p><a href="#dat-lich">Nhờ Xile tư vấn <span aria-hidden>↗</span></a></div></div></section>
<section className="letter section wrap"><p className="eyebrow">MỘT LỜI NHẮN TỪ XILE</p><span className="quote-mark" aria-hidden>“</span><h2>Làn da khỏe đẹp là hành trình<br/>{' '}của <em>sự kiên nhẫn</em><br/>{' '}và lựa chọn đúng đắn.</h2><p>Không cần so sánh làn da của mình với ai khác. Mỗi người có một hành trình riêng để học cách quan tâm và chăm sóc bản thân.</p><span className="signature">Xile Beauty Spa</span></section>
<section className="prepare wrap"><div><p className="eyebrow">MANG THEO MỘT CHÚT CHỦ ĐỘNG</p><h2>Trước buổi hẹn,<br/>{' '}hãy nghĩ về <em>ba điều này.</em></h2></div><ol><li>Điều bạn quan tâm nhất về làn da hiện tại.</li><li>Sản phẩm hoặc dịch vụ chăm da bạn đang sử dụng.</li><li>Khoảng thời gian và ngân sách bạn muốn dành cho buổi chăm sóc.</li></ol></section>
<section className="section wrap faq" id="hoi-dap"><div><p className="eyebrow">05 / ĐIỀU BẠN MUỐN BIẾT</p><h2>Cứ hỏi nhé<br/>{' '}<em>Xile lắng nghe.</em></h2><a className="text-link" href="tel:0909722408">0909 722 408 ↗</a></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="booking" id="dat-lich"><div className="wrap booking-grid"><div className="booking-copy"><p className="eyebrow">MỘT BUỔI HẸN DÀNH CHO LÀN DA</p><h2>Bắt đầu bằng<br/>{' '}một cuộc <em>trò chuyện.</em></h2><p>Chọn dịch vụ bạn quan tâm, để Xile cùng bạn trao đổi trước khi hẹn một buổi chăm sóc.</p><a className="phone" href="tel:0909722408">0909 722 408</a><p>67 Hưng Phú, Quận 8<br/>{' '}TP. Hồ Chí Minh</p></div><BookingForm/></div></section>
</main><footer className="wrap"><Brand/><p>Chăm sóc da bằng sự kiên nhẫn.<br/>{' '}Xile Beauty Spa · 67 Hưng Phú, Quận 8</p><a href="https://www.facebook.com/xilebeautyspa/" target="_blank" rel="noopener noreferrer">Facebook ↗</a><div className="footer-bottom"><span>© {new Date().getFullYear()} Xile Beauty Spa</span><p>Nội dung giới thiệu dịch vụ chăm sóc da, không thay thế tư vấn hoặc điều trị y khoa. Kết quả tùy từng người.</p></div></footer><div className="mobile-bar"><a href="tel:0909722408">Gọi Xile</a><a href="#dat-lich">Đặt lịch tư vấn <span aria-hidden>↗</span></a></div>
</>}
