'use client';
import {useEffect,useState} from 'react';
import {services,servicePrice} from '@/app/services';
export default function BookingForm(){
 const [selected,setSelected]=useState('consult');const [errors,setErrors]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{const choose=(event:MouseEvent)=>{const target=event.target instanceof Element?event.target.closest<HTMLAnchorElement>('a[data-service]'):null;const id=target?.dataset.service;if(id&&services.some(s=>s.id===id)){setSelected(id);setStatus('');setMessage('');}};document.addEventListener('click',choose);return()=>document.removeEventListener('click',choose);},[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setStatus('');setMessage('');const form=new FormData(event.currentTarget);const name=String(form.get('name')??'').trim();const phone=String(form.get('phone')??'').replace(/[\s().-]/g,'');const next:Record<string,string>={};if(name.length<2)next.name='Bạn nhập tên từ 2 ký tự nhé';if(!/^(0[35789]\d{8}|\+84[35789]\d{8})$/.test(phone))next.phone='Vui lòng nhập số điện thoại Việt Nam hợp lệ.';if(!form.get('consent'))next.consent='Vui lòng đồng ý để Xile liên hệ về lịch hẹn.';setErrors(next);if(Object.keys(next).length){const first=Object.keys(next)[0];event.currentTarget.querySelector<HTMLInputElement>(`[name="${first}"]`)?.focus();return;}const service=services.find(s=>s.id===selected);const text=`Chào Xile, mình là ${name}. Mình muốn ${service?`tìm hiểu ${service.name} (${servicePrice(service)})`:'được tư vấn dịch vụ chăm sóc da'}. Số điện thoại: ${phone}. Xile tư vấn giúp mình khung giờ phù hợp nhé`;const endpoint=process.env.NEXT_PUBLIC_BOOKING_API_URL;
 if(!endpoint){setMessage(text);setStatus('Yêu cầu đã được soạn. Bạn sao chép và gửi qua Facebook để Xile tiếp nhận nhé Thông tin chưa được gửi tự động.');return;}
 setBusy(true);try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,serviceId:selected,consent:true,source:'xile-skin-care'}),signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error();setStatus('Xile đã nhận yêu cầu. Lịch hẹn sẽ được xác nhận sau khi trao đổi trực tiếp với bạn.');}catch{setStatus('Chưa gửi được yêu cầu. Vui lòng thử lại hoặc gọi Xile qua 0909 722 408.');}finally{setBusy(false);}
 }
 return <form className="booking-form" onSubmit={submit} noValidate><div className="form-heading"><span className="eyebrow">BẮT ĐẦU TỪ VIỆC LẮNG NGHE DA</span><h3>Bạn muốn Xile chăm sóc thế nào?</h3><p>Chọn một gói, hoặc để Xile cùng bạn tìm trải nghiệm phù hợp.</p></div><label htmlFor="service">Gói bạn quan tâm</label><select id="service" name="service" value={selected} onChange={e=>{setSelected(e.target.value);setMessage('');setStatus('');}}><option value="consult">Mình cần Xile tư vấn</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} — {servicePrice(s)}</option>)}</select><div className="field-grid"><div><label htmlFor="name">Tên của bạn</label><input id="name" name="name" autoComplete="name" maxLength={80} placeholder="Xile gọi bạn là…" aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined}/>{errors.name&&<p className="error" id="name-error">{errors.name}</p>}</div><div><label htmlFor="phone">Số điện thoại</label><input id="phone" name="phone" type="tel" inputMode="tel" autoComplete="tel" maxLength={20} placeholder="090 000 0000" aria-invalid={!!errors.phone} aria-describedby={errors.phone?'phone-error':undefined}/>{errors.phone&&<p className="error" id="phone-error">{errors.phone}</p>}</div></div><label className="consent"><input type="checkbox" name="consent" aria-describedby={errors.consent?'consent-error':undefined}/><span>Tôi đồng ý để Xile liên hệ về yêu cầu đặt lịch này.</span></label>{errors.consent&&<p id="consent-error" className="error">{errors.consent}</p>}<button className="button" type="submit" disabled={busy}>{busy?'Đang gửi…':'Tiếp tục đặt lịch'}<span aria-hidden>↗</span></button><p className="form-note">Chưa cần thanh toán · Xác nhận lịch trực tiếp với Xile</p><div role="status" aria-live="polite">{status&&<p className="status">{status}</p>}</div>{message&&<div className="message-ready"><label htmlFor="message">Nội dung để gửi Xile</label><textarea id="message" readOnly value={message}/><button className="copy-button" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(message);setStatus('Đã sao chép. Mở Facebook và dán tin nhắn để gửi cho Xile.');}catch{setStatus('Bạn có thể chọn và sao chép nội dung trong ô bên dưới, rồi gửi qua Facebook.');}}}>Sao chép tin nhắn</button><a href="https://www.facebook.com/xilebeautyspa/" target="_blank" rel="noopener noreferrer" className="button">Mở Facebook của Xile<span aria-hidden>↗</span></a></div>}</form>
}
